### ISSUE TITLE
collect_node_diag trips over comments in cassandra.yaml

### ISSUE THREAD

**Issue by driehuis** [DataStax-Toolkit/diagnostic-collection#52]
DSE is shipped with a cassandra.conf that has this line:
```
broadcast_address: # Leave unset or clear...
```

We had left the comment to remind ourselves that empty is a valid option. But as it turns out, collect_node_diag.sh trips over it:
```
Collecting data from node broadcast_address: # Leave unset or clear...
Can't execute cqlsh command, exit code: 1. If you're have cluster with authentication,
please pass the option -c with user name/password and other options, like:
-c '-u username -p password'
If you have SSL enabled for client connections, pass --ssl in -c
```

No data is collected. This is a similar but different to issue #15. The system is a fully up-to-date RHEL7 with sed 4.2.2-7 in case the suspicion goes there.

The workaround is trivial, removing these comments solves it fully.

**Comment by msmygit** [comment]
@driehuis thanks for reporting this, but this is not an issue at all as DSE's `cassandra.yaml` comes with the following surrounding the `broadcast_address` property,

```
# Address to broadcast to other database nodes.
# Leaving this blank will set it to the same value as listen_address
# broadcast_address: 1.2.3.4
```

So, it is very possible that somebody might have just edited that to put the command right beside the property. I am closing this issue as a non-issue, but please feel free to re-open if it is otherwise. Thanks again for building this community!
